# Set back-tick as prefix key.
# Also, type back-tick on double press.
unbind C-b
set-option -g prefix `
bind ` send-prefix

# shortcut to reload configs.
bind r source-file ~/.tmux.conf \; display-message "Config reloaded."

# setting the windows and panes index from 1.
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on
